# Outline for things to do

## 1. Loading documents for each dataset into Pinecone
- Use dataset name as metadata -> Add 1 column besides the query so that we can search by metadata -> Faster and more accurate

## 2. Create a dataframe of query:
- Columns: query_id, query, dataset_name

## 3. Things to test:

### 3.1 Simple RAG submission:
- Use raw vectore store to retrieve the top-10 most relevant documents to the query

### 3.2 Vector Search + RAG Fusion

### 3.3 Hybrid search + Reranking

In [1]:
import os
import numpy as np
import pandas as pd

from dotenv import load_dotenv
from langchain_core.documents import Document
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_google_genai import GoogleGenerativeAIEmbeddings
from financerag.task import *
from financerag.retrieval import DenseRetrieval
from langchain_text_splitters.base import TextSplitter
pd.set_option('display.max_colwidth', 400)

In [2]:
load_dotenv(".env")
GG_API_KEY = os.environ.get('GOOGLE_API_KEY')
PINECONE_API_KEY = os.environ.get('PINECONE_API_KEY')
LANGSMITH_API_KEY = os.environ.get('LANGSMITH_API_KEY')

In [3]:
# Set up vector database
import faiss
from langchain_community.docstore.in_memory import InMemoryDocstore
from langchain_community.vectorstores import FAISS
embeddings = GoogleGenerativeAIEmbeddings(model = "models/text-embedding-004")
index = faiss.IndexFlatL2(len(embeddings.embed_query("hello world")))

vector_store = FAISS(
    embedding_function=embeddings,
    index=index,
    docstore=InMemoryDocstore(),
    index_to_docstore_id={},
)

In [3]:
# Get dataset name first
import os
dataset_names = []
for f in os.listdir('finance_dataset'):
    if f.endswith("tsv"):
       dataset_names.append(f.split('_')[0])
dataset_names

['MultiHeirtt',
 'FinQA',
 'FinanceBench',
 'ConvFinQA',
 'FinQABench',
 'TATQA',
 'FinDER']

In [ ]:
text_splitter = RecursiveCharacterTextSplitter(chunk_size=2000, chunk_overlap=300)

In [8]:
for dataset_name in dataset_names:
    task_variable = f"{dataset_name.lower()}_task"
    script_string = f"""
    # {dataset_name} Task
    print(f"{dataset_name} task")
    {task_variable} = {dataset_name}Task()
    {task_variable}.load()
    {task_variable}_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = {task_variable}.metadata.dataset_name)
    {task_variable}_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = {task_variable}.corpus, saved_index = True)
    {task_variable}.retrieve(retriever = {task_variable}_retriever, top_k = 100)
    {task_variable}.save_retrieved_results()
    """
    print(script_string)

    # MultiHeirtt Task
    print(f"MultiHeirtt task")
    multiheirtt_task = MultiHeirttTask()
    multiheirtt_task.load()
    multiheirtt_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = multiheirtt_task.metadata.dataset_name)
    multiheirtt_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = multiheirtt_task.corpus, saved_index = True)
    multiheirtt_task.retrieve(retriever = multiheirtt_task_retriever, top_k = 100)
    multiheirtt_task.save_retrieved_results()


    # FinQA Task
    print(f"FinQA task")
    finqa_task = FinQATask()
    finqa_task.load()
    finqa_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = finqa_task.metadata.dataset_name)
    finqa_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = finqa_task.corpus, saved_index = True)
    finqa_task.retrieve(retriever = finqa_task_retriever, top_k = 100)
    finqa_task.save_retrieved_results()


    # FinanceBench Task
    print(f"FinanceBench task")
    financebench_task = FinanceBenchTask()
    financebench_task.load()
    financebench_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = financebench_task.metadata.dataset_name)
    financebench_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = financebench_task.corpus, saved_index = True)
    financebench_task.retrieve(retriever = financebench_task_retriever, top_k = 100)
    financebench_task.save_retrieved_results()


    # ConvFinQA Task
    print(f"ConvFinQA task")
    convfinqa_task = ConvFinQATask()
    convfinqa_task.load()
    convfinqa_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = convfinqa_task.metadata.dataset_name)
    convfinqa_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = convfinqa_task.corpus, saved_index = True)
    convfinqa_task.retrieve(retriever = convfinqa_task_retriever, top_k = 100)
    convfinqa_task.save_retrieved_results()


    # FinQABench Task
    print(f"FinQABench task")
    finqabench_task = FinQABenchTask()
    finqabench_task.load()
    finqabench_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = finqabench_task.metadata.dataset_name)
    finqabench_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = finqabench_task.corpus, saved_index = True)
    finqabench_task.retrieve(retriever = finqabench_task_retriever, top_k = 100)
    finqabench_task.save_retrieved_results()


    # TATQA Task
    print(f"TATQA task")
    tatqa_task = TATQATask()
    tatqa_task.load()
    tatqa_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = tatqa_task.metadata.dataset_name)
    tatqa_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = tatqa_task.corpus, saved_index = True)
    tatqa_task.retrieve(retriever = tatqa_task_retriever, top_k = 100)
    tatqa_task.save_retrieved_results()


    # FinDER Task
    print(f"FinDER task")
    finder_task = FinDERTask()
    finder_task.load()
    finder_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = finder_task.metadata.dataset_name)
    finder_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = finder_task.corpus, saved_index = True)
    finder_task.retrieve(retriever = finder_task_retriever, top_k = 100)
    finder_task.save_retrieved_results()

In [15]:
%%time
# FinanceBench Task
print(f"FinanceBench task")
financebench_task = FinanceBenchTask()
financebench_task.load()
financebench_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = financebench_task.metadata.dataset_name)
financebench_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = financebench_task.corpus, saved_index = True)
financebench_task.retrieve(retriever = financebench_task_retriever, top_k = 100)
financebench_task.save_retrieved_results()

FinanceBench task

Loading document:: 100%|██████████| 180/180 [00:00<00:00, 7132.09it/s]

Successfully saved index of vector store to path : faiss_index/financebench_index

Retrieving result::   1%|          | 1/150 [00:00<00:50,  2.96it/s]

Len key of docs dict :2

Retrieving result::   1%|▏         | 2/150 [00:00<00:49,  2.97it/s]

Len key of docs dict :1

Retrieving result::   2%|▏         | 3/150 [00:01<00:52,  2.78it/s]

Len key of docs dict :3

Retrieving result::   3%|▎         | 4/150 [00:01<00:52,  2.79it/s]

Len key of docs dict :3

Retrieving result::   3%|▎         | 5/150 [00:01<00:54,  2.67it/s]

Len key of docs dict :2

Retrieving result::   4%|▍         | 6/150 [00:02<00:53,  2.69it/s]

Len key of docs dict :3

Retrieving result::   5%|▍         | 7/150 [00:02<00:51,  2.77it/s]

Len key of docs dict :2

Retrieving result::   5%|▌         | 8/150 [00:02<00:50,  2.83it/s]

Len key of docs dict :3

Retrieving result::   6%|▌         | 9/150 [00:03<00:50,  2.82it/s]

Len key of docs dict :2

Retrieving result::   7%|▋         | 10/150 [00:03<00:50,  2.79it/s]

Len key of docs dict :3

Retrieving result::   7%|▋         | 11/150 [00:03<00:49,  2.79it/s]

Len key of docs dict :1

Retrieving result::   8%|▊         | 12/150 [00:04<00:48,  2.85it/s]

Len key of docs dict :3

Retrieving result::   9%|▊         | 13/150 [00:04<00:48,  2.82it/s]

Len key of docs dict :3

Retrieving result::   9%|▉         | 14/150 [00:04<00:47,  2.86it/s]

Len key of docs dict :2

Retrieving result::  10%|█         | 15/150 [00:05<00:46,  2.90it/s]

Len key of docs dict :2

Retrieving result::  11%|█         | 16/150 [00:05<00:53,  2.49it/s]

Len key of docs dict :2

Retrieving result::  11%|█▏        | 17/150 [00:06<00:51,  2.58it/s]

Len key of docs dict :2

Retrieving result::  12%|█▏        | 18/150 [00:06<00:50,  2.63it/s]

Len key of docs dict :0

Retrieving result::  13%|█▎        | 19/150 [00:07<00:52,  2.52it/s]

Len key of docs dict :3

Retrieving result::  13%|█▎        | 20/150 [00:07<00:49,  2.61it/s]

Len key of docs dict :3

Retrieving result::  14%|█▍        | 21/150 [00:07<00:48,  2.65it/s]

Len key of docs dict :3

Retrieving result::  15%|█▍        | 22/150 [00:08<00:49,  2.59it/s]

Len key of docs dict :3

Retrieving result::  15%|█▌        | 23/150 [00:08<00:48,  2.62it/s]

Len key of docs dict :2

Retrieving result::  16%|█▌        | 24/150 [00:08<00:47,  2.67it/s]

Len key of docs dict :2

Retrieving result::  17%|█▋        | 25/150 [00:09<00:46,  2.72it/s]

Len key of docs dict :2

Retrieving result::  17%|█▋        | 26/150 [00:09<00:45,  2.73it/s]

Len key of docs dict :3

Retrieving result::  18%|█▊        | 27/150 [00:10<00:48,  2.54it/s]

Len key of docs dict :3

Retrieving result::  19%|█▊        | 28/150 [00:10<00:46,  2.62it/s]

Len key of docs dict :2

Retrieving result::  19%|█▉        | 29/150 [00:10<00:45,  2.69it/s]

Len key of docs dict :3

Retrieving result::  20%|██        | 30/150 [00:11<00:44,  2.72it/s]

Len key of docs dict :3

Retrieving result::  21%|██        | 31/150 [00:11<00:42,  2.78it/s]

Len key of docs dict :3

Retrieving result::  21%|██▏       | 32/150 [00:11<00:41,  2.82it/s]

Len key of docs dict :2

Retrieving result::  22%|██▏       | 33/150 [00:12<00:41,  2.81it/s]

Len key of docs dict :3

Retrieving result::  22%|██▏       | 33/150 [00:12<00:45,  2.59it/s]

KeyboardInterrupt:

In [ ]:
from sentence_transformers import CrossEncoder

In [8]:
# 1. Load a pretrained CrossEncoder model
model = CrossEncoder("cross-encoder/ms-marco-MiniLM-L6-v2", device = 'cpu')

# The texts for which to predict similarity scores
query = "How many people live in Berlin?"
passages = [
    "Berlin had a population of 3,520,031 registered inhabitants in an area of 891.82 square kilometers.",
    "Berlin has a yearly total of about 135 million day visitors, making it one of the most-visited cities in the European Union.",
    "In 2013 around 600,000 Berliners were registered in one of the more than 2,300 sport and fitness clubs.",
]

# 2a. Either predict scores pairs of texts
scores = model.predict([(query, passage) for passage in passages])
print(scores)
# => [8.607139 5.506266 6.352977]

# 2b. Or rank a list of passages for a query
ranks = model.rank(query, passages, return_documents=True)

print("Query:", query)
for rank in ranks:
    print(f"- #{rank['corpus_id']} ({rank['score']:.2f}): {rank['text']}")

AttributeError: module 'torch' has no attribute 'get_default_device'

In [11]:
!pip install --upgrade pip

Requirement already satisfied: pip in ./.venv/lib/python3.9/site-packages (23.0.1)
Collecting pip
  Using cached pip-25.1.1-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.0.1
    Uninstalling pip-23.0.1:
      Successfully uninstalled pip-23.0.1
Successfully installed pip-25.1.1

In [13]:
!pip3 install torch==2.7.0

ERROR: Could not find a version that satisfies the requirement torch==2.7.0 (from versions: 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2)
ERROR: No matching distribution found for torch==2.7.0

In [5]:
import torch
torch.__version__

'2.2.2'

In [ ]:

# MultiHeirtt Task
print(f"MultiHeirtt task")
multiheirtt_task = MultiHeirttTask()
multiheirtt_task.load()
multiheirtt_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = multiheirtt_task.metadata.dataset_name)
multiheirtt_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = multiheirtt_task.corpus, saved_index = True)
multiheirtt_task.retrieve(retriever = multiheirtt_task_retriever, top_k = 100)
multiheirtt_task.save_retrieved_results()


# FinQA Task
print(f"FinQA task")
finqa_task = FinQATask()
finqa_task.load()
finqa_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = finqa_task.metadata.dataset_name)
finqa_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = finqa_task.corpus, saved_index = True)
finqa_task.retrieve(retriever = finqa_task_retriever, top_k = 100)
finqa_task.save_retrieved_results()


# ConvFinQA Task
print(f"ConvFinQA task")
convfinqa_task = ConvFinQATask()
convfinqa_task.load()
convfinqa_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = convfinqa_task.metadata.dataset_name)
convfinqa_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = convfinqa_task.corpus, saved_index = True)
convfinqa_task.retrieve(retriever = convfinqa_task_retriever, top_k = 100)
convfinqa_task.save_retrieved_results()


# FinQABench Task
print(f"FinQABench task")
finqabench_task = FinQABenchTask()
finqabench_task.load()
finqabench_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = finqabench_task.metadata.dataset_name)
finqabench_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = finqabench_task.corpus, saved_index = True)
finqabench_task.retrieve(retriever = finqabench_task_retriever, top_k = 100)
finqabench_task.save_retrieved_results()


# TATQA Task
print(f"TATQA task")
tatqa_task = TATQATask()
tatqa_task.load()
tatqa_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = tatqa_task.metadata.dataset_name)
tatqa_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = tatqa_task.corpus, saved_index = True)
tatqa_task.retrieve(retriever = tatqa_task_retriever, top_k = 100)
tatqa_task.save_retrieved_results()


# FinDER Task
print(f"FinDER task")
finder_task = FinDERTask()
finder_task.load()
finder_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = finder_task.metadata.dataset_name)
finder_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = finder_task.corpus, saved_index = True)
finder_task.retrieve(retriever = finder_task_retriever, top_k = 100)
finder_task.save_retrieved_results()

In [7]:
a = ['s', 'a', 'd']
' '.join(a)

's a d'

In [ ]:
# MultiHeirtt Task
multiheirtt_task = MultiHeirttTask()
multiheirtt_task.load()
multiheirtt_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = multiheirtt_task.metadata.dataset_name)
multiheirtt_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = multiheirtt_task.corpus, saved_index = True)
multiheirtt_task.retrieve(retriever = multiheirtt_task_retriever)
multiheirtt_task.save_retrieved_results()

Loading document:: 100%|██████████| 10475/10475 [00:00<00:00, 42579.02it/s]

Successfully saved index of vector store to path : faiss_index/multiheirtt_index
Saved result successfully to ./financerag_result/multiheirtt_result.csv!

In [ ]:
# FinQA Task
finqa_task = FinQATask()
finqa_task.load()
finqa_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = finqa_task.metadata.dataset_name)
finqa_task_retriever.load_corpus_for_searching_without_splitting(finqa_task.corpus, saved_index = True)
finqa_task.retrieve(retriever = finqa_task_retriever)
finqa_task.save_retrieved_results()

Loading document: 100%|██████████| 2789/2789 [00:00<00:00, 151775.10it/s]

Successfully saved index of vector store to path : faiss_index/finqa_index

Retrieving result:: 100%|██████████| 1147/1147 [07:21<00:00,  2.60it/s]

Saved result successfully to ./financerag_result/finqa_result.csv!

In [13]:

# FinanceBench Task
financebench_task = FinanceBenchTask()
financebench_task.load()
financebench_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = financebench_task.metadata.dataset_name)
financebench_task_retriever.load_corpus_for_searching(financebench_task.corpus, saved_index = True)
financebench_task.retrieve(retriever = financebench_task_retriever)
financebench_task.save_retrieved_results()

Loading document: 100%|██████████| 180/180 [00:00<00:00, 131942.45it/s]

Successfully saved index of vector store to path : faiss_index/financebench_index

Retrieving result:: 100%|██████████| 150/150 [01:02<00:00,  2.42it/s]

Saved result successfully to ./financerag_result/financebench_result.csv!

In [ ]:
# ConvFinQA Task
convfinqa_task = ConvFinQATask()
convfinqa_task.load()
convfinqa_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = convfinqa_task.metadata.dataset_name)
convfinqa_task_retriever.load_corpus_for_searching_without_splitting(convfinqa_task.corpus, saved_index = True)
convfinqa_task.retrieve(retriever = convfinqa_task_retriever)
convfinqa_task.save_retrieved_results()

Loading document: 100%|██████████| 2066/2066 [00:00<00:00, 129481.68it/s]

Successfully saved index of vector store to path : faiss_index/convfinqa_index

Retrieving result:: 100%|██████████| 421/421 [02:37<00:00,  2.67it/s]

Saved result successfully to ./financerag_result/convfinqa_result.csv!

In [15]:

# FinQABench Task
finqabench_task = FinQABenchTask()
finqabench_task.load()
finqabench_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = finqabench_task.metadata.dataset_name)
finqabench_task_retriever.load_corpus_for_searching(finqabench_task.corpus, saved_index = True)
finqabench_task.retrieve(retriever = finqabench_task_retriever)
finqabench_task.save_retrieved_results()

Loading document: 100%|██████████| 92/92 [00:00<00:00, 89592.75it/s]

Successfully saved index of vector store to path : faiss_index/finqabench_index

Retrieving result:: 100%|██████████| 100/100 [00:36<00:00,  2.75it/s]

Saved result successfully to ./financerag_result/finqabench_result.csv!

In [ ]:

# TATQA Task
tatqa_task = TATQATask()
tatqa_task.load()
tatqa_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = tatqa_task.metadata.dataset_name)
tatqa_task_retriever.load_corpus_for_searching_without_splitting(tatqa_task.corpus, saved_index = True)
tatqa_task.retrieve(retriever = tatqa_task_retriever)
tatqa_task.save_retrieved_results()

Loading document: 100%|██████████| 2756/2756 [00:00<00:00, 182551.12it/s]

Successfully saved index of vector store to path : faiss_index/tatqa_index

Retrieving result:: 100%|██████████| 1663/1663 [15:14<00:00,  1.82it/s]

Saved result successfully to ./financerag_result/tatqa_result.csv!

In [ ]:

# FinDER Task
finder_task = FinDERTask()
finder_task.load()
finder_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = finder_task.metadata.dataset_name)
finder_task_retriever.load_corpus_for_searching_without_splitting(finder_task.corpus, saved_index = True)
finder_task.retrieve(retriever = finder_task_retriever)
finder_task.save_retrieved_results()

Loading document: 100%|██████████| 13862/13862 [00:00<00:00, 20056.98it/s]

Successfully saved index of vector store to path : faiss_index/finder_index

Retrieving result:: 100%|██████████| 216/216 [01:57<00:00,  1.84it/s]

Saved result successfully to ./financerag_result/finder_result.csv!

In [ ]:
1: Recusplitter(chunk_size = 1000, overlap_size = 20)
2 :SemanticSplitter()Hello how are you

1: hello,how , are you
2. hello | how are you

In [16]:
final_result = pd.DataFrame(columns = ['query_id', 'corpus_id'])

for dataset_name in dataset_names:
    df = pd.read_csv(f"financerag_result/{dataset_name.lower()}_result.csv")
    final_result = pd.concat([final_result, df], axis = 0)

final_result

       query_id     corpus_id
0     q82d4c6ec     d8177a896
1     q82d4c6ec     d8d3fbbaa
2     q82d4c6ec     d85eb42c0
3     q82d4c6ec     d8e817e40
4     q82d4c6ec     d8bb12b52
...         ...           ...
2155     q00218  ADBE20230512
2156     q00218  TSLA20231025
2157     q00218  CPNG20230812
2158     q00218   LIN20230185
2159     q00218     V20230334

[46710 rows x 2 columns]

In [17]:
pd.read_csv('submission.csv')

        query_id      corpus_id
0      q82d4c6ec      d8e404704
1      q82d4c6ec      d87914156
2      q82d4c6ec      d8a3219a8
3      q82d4c6ec      d8c22a07a
4      q82d4c6ec      d88e1c5b2
...          ...            ...
44538     q00218  GOOGL20231203
44539     q00218    JPM20234729
44540     q00218      V20231584
44541     q00218    JPM20237319
44542     q00218      V20231597

[44543 rows x 2 columns]

In [20]:
pd.read_csv('finance_dataset/sample_submission_.csv')

        query_id  corpus_id
0      qd496c6a0  dd4b92b32
1      qd496c6a0  dd4ba2a5a
2      qd496c6a0  dd4be1f98
3      qd496c6a0  dd4ba07d2
4      qd496c6a0  dd4ba02f0
...          ...        ...
46681  q1a741e68  d1b3afaba
46682  q1a741e68  d1b34e18e
46683  q1a741e68  d1b36065e
46684  q1a741e68  d1b33d05a
46685  q1a741e68  d1b32d114

[46686 rows x 2 columns]

In [18]:
final_result.to_csv('submission_bm25.csv', index = False)

In [22]:
final_result.drop_duplicates(subset = ['query_id'])

       query_id      corpus_id
0     q82d4c6ec      d8e404704
10    q855a35a0      d89a6ea36
20    q85384530      d8ce7fc30
30    q842c8af2      d88465f0a
40    q85451756      d8646ec7e
...         ...            ...
2094     q00214  BRK.A20230009
2104     q00215  BRK.A20230404
2114     q00216  BRK.A20232401
2124     q00217  BRK.A20230062
2134     q00218  BRK.A20230594

[4659 rows x 2 columns]

In [28]:
final_queries = pd.DataFrame(columns = ['_id', 'title', 'text'])

for dataset_name in dataset_names:
    df = pd.read_json(f"finance_dataset/{dataset_name.lower()}_queries.jsonl/queries.jsonl", lines = True)
    final_queries = pd.concat([final_queries, df], axis = 0)

final_queries

           _id title                                               text
0    q82d4c6ec        What was the sum of Fourth Quarter without tho...
1    q855a35a0        In which section is Interest income smaller th...
2    q85384530        If Total Forward Hedged Revenues develops with...
3    q842c8af2        what was the ratio of the purchase in december...
4    q85451756        what is the highest total amount of segment in...
..         ...   ...                                                ...
211     q00214        How many distinct insurance underwriting group...
212     q00215        What is the ticker symbol for Berkshire Hathaw...
213     q00216        What is the largest operating segment of the B...
214     q00217        Source of invested assets of insurance busines...
215     q00218                                     Float as of 2023 BRK

[4671 rows x 3 columns]

In [4]:
for dataset_name in dataset_names:
    task_variable = f"{dataset_name.lower()}_task"
    script_string = f"""
    # {dataset_name} Task
    print(f"{dataset_name} task")
    {task_variable} = {dataset_name}Task()
    {task_variable}.load()
    {task_variable}_bm25_retriever = BM25_Retriever()
    {task_variable}.retrieve(retriever = {task_variable}_bm25_retriever, top_k = 10)
    {task_variable}.save_retrieved_results()
    """
    print(script_string)

    # MultiHeirtt Task
    print(f"MultiHeirtt task")
    multiheirtt_task = MultiHeirttTask()
    multiheirtt_task.load()
    multiheirtt_task_bm25_retriever = BM25_Retriever()
    multiheirtt_task.retrieve(retriever = multiheirtt_task_bm25_retriever, top_k = 10)
    multiheirtt_task.save_retrieved_results()


    # FinQA Task
    print(f"FinQA task")
    finqa_task = FinQATask()
    finqa_task.load()
    finqa_task_bm25_retriever = BM25_Retriever()
    finqa_task.retrieve(retriever = finqa_task_bm25_retriever, top_k = 10)
    finqa_task.save_retrieved_results()


    # FinanceBench Task
    print(f"FinanceBench task")
    financebench_task = FinanceBenchTask()
    financebench_task.load()
    financebench_task_bm25_retriever = BM25_Retriever()
    financebench_task.retrieve(retriever = financebench_task_bm25_retriever, top_k = 10)
    financebench_task.save_retrieved_results()


    # ConvFinQA Task
    print(f"ConvFinQA task")
    convfinqa_task = ConvFinQATask()
    convfinqa_task.load()
    convfinqa_task_bm25_retriever = BM25_Retriever()
    convfinqa_task.retrieve(retriever = convfinqa_task_bm25_retriever, top_k = 10)
    convfinqa_task.save_retrieved_results()


    # FinQABench Task
    print(f"FinQABench task")
    finqabench_task = FinQABenchTask()
    finqabench_task.load()
    finqabench_task_bm25_retriever = BM25_Retriever()
    finqabench_task.retrieve(retriever = finqabench_task_bm25_retriever, top_k = 10)
    finqabench_task.save_retrieved_results()


    # TATQA Task
    print(f"TATQA task")
    tatqa_task = TATQATask()
    tatqa_task.load()
    tatqa_task_bm25_retriever = BM25_Retriever()
    tatqa_task.retrieve(retriever = tatqa_task_bm25_retriever, top_k = 10)
    tatqa_task.save_retrieved_results()


    # FinDER Task
    print(f"FinDER task")
    finder_task = FinDERTask()
    finder_task.load()
    finder_task_bm25_retriever = BM25_Retriever()
    finder_task.retrieve(retriever = finder_task_bm25_retriever, top_k = 10)
    finder_task.save_retrieved_results()

In [5]:
from financerag.retrieval import BM25, BM25_Retriever

In [15]:
%%time
# MultiHeirtt Task
print(f"MultiHeirtt task")
multiheirtt_task = MultiHeirttTask()
multiheirtt_task.load()
multiheirtt_task_bm25_retriever = BM25_Retriever()
multiheirtt_task.retrieve(retriever = multiheirtt_task_bm25_retriever, top_k = 10)
multiheirtt_task.save_retrieved_results()


# FinQA Task
print(f"FinQA task")
finqa_task = FinQATask()
finqa_task.load()
finqa_task_bm25_retriever = BM25_Retriever()
finqa_task.retrieve(retriever = finqa_task_bm25_retriever, top_k = 10)
finqa_task.save_retrieved_results()


# FinanceBench Task
print(f"FinanceBench task")
financebench_task = FinanceBenchTask()
financebench_task.load()
financebench_task_bm25_retriever = BM25_Retriever()
financebench_task.retrieve(retriever = financebench_task_bm25_retriever, top_k = 10)
financebench_task.save_retrieved_results()


# ConvFinQA Task
print(f"ConvFinQA task")
convfinqa_task = ConvFinQATask()
convfinqa_task.load()
convfinqa_task_bm25_retriever = BM25_Retriever()
convfinqa_task.retrieve(retriever = convfinqa_task_bm25_retriever, top_k = 10)
convfinqa_task.save_retrieved_results()


# # FinQABench Task
print(f"FinQABench task")
finqabench_task = FinQABenchTask()
finqabench_task.load()
finqabench_task_bm25_retriever = BM25_Retriever()
finqabench_task.retrieve(retriever = finqabench_task_bm25_retriever, top_k = 10)
finqabench_task.save_retrieved_results()


# TATQA Task
print(f"TATQA task")
tatqa_task = TATQATask()
tatqa_task.load()
tatqa_task_bm25_retriever = BM25_Retriever()
tatqa_task.retrieve(retriever = tatqa_task_bm25_retriever, top_k = 10)
tatqa_task.save_retrieved_results()


# FinDER Task
print(f"FinDER task")
finder_task = FinDERTask()
finder_task.load()
finder_task_bm25_retriever = BM25_Retriever()
finder_task.retrieve(retriever = finder_task_bm25_retriever, top_k = 10)
finder_task.save_retrieved_results()

MultiHeirtt task
Saved result successfully to ./financerag_result/multiheirtt_result.csv!
FinQA task
Saved result successfully to ./financerag_result/finqa_result.csv!
FinanceBench task
Saved result successfully to ./financerag_result/financebench_result.csv!
ConvFinQA task
Saved result successfully to ./financerag_result/convfinqa_result.csv!
FinQABench task
Saved result successfully to ./financerag_result/finqabench_result.csv!
TATQA task
Saved result successfully to ./financerag_result/tatqa_result.csv!
FinDER task
Saved result successfully to ./financerag_result/finder_result.csv!
CPU times: user 3min 11s, sys: 4.49 s, total: 3min 16s
Wall time: 3min 17s

In [12]:
from nltk.tokenize import word_tokenize
from langchain_community.retrievers.bm25 import BM25Retriever
retriever = BM25Retriever.from_documents(
    [
        Document(page_content="foo"),
        Document(page_content="bar"),
        Document(page_content="world"),
        Document(page_content="hello"),
        Document(page_content="foo bar"),
    ],
    k=2,
    preprocess_func=word_tokenize,
)

result = retriever.invoke("bar")
result

[Document(metadata={}, page_content='bar'),
 Document(metadata={}, page_content='foo bar')]

In [7]:
multiheirtt_task.queries

{'q82d4c6ec': 'What was the sum of Fourth Quarter without those Fourth Quarter smaller than 0, in 2012? (in million)',
 'q855a35a0': 'In which section is Interest income smaller thanProvision for credit losses?',
 'q85384530': 'If Total Forward Hedged Revenues develops with the same growing rate in 2019, what will it reach in 2020? (in million)',
 'q842c8af2': 'what was the ratio of the purchase in december 2012 to the purchase in january 2013',
 'q85451756': 'what is the highest total amount of segment in 2015?',
 'q85737826': 'How many kinds of period is the value of Customer deposits more than the 50% of the total value of Customer deposits?',
 'q827742c4': 'How many Amount for Credit Card (a) exceed the average of Amount for Credit Card (a) in 2012?',
 'q81e448f2': 'considering the years 2015-2016 , what was the decrease observed in the expense for severance and other benefits?',
 'q82305cc4': "What's the total amount of active, iSharesETFs and Non-ETF index in 2016 in equity (in million)",
 'q81a100a6': 'for the terrestar acquisition what will the final cash purchase price be in millions paid upon closing?',
 'q847a1ac4': 'what is the percent change of interest paid between 2016 and 2017?',
 'q82bb179c': 'how many years did it take to close the pilgrim plant after after its last refueling?',
 'q82787914': 'The total amount of which section ranks first for Years Ended December 31, for Credit loss impairments? (in million)',
 'q847c4394': 'as of december 31 , 2015 , what was the maximum premium on the dp&l preferred stock?',
 'q85306054': 'what was the ratio of the share repurchase in 2014 to 2015',
 'q81b147b8': 'In what sections is Granted greater than 100 for Options For Shares?',
 'q81a86062': 'Which element makes up more than 20 % of the total for Carrying amount of Total in 2009?',
 'q852ed734': 'what percent did the balance increase from the beginning of 2016 to the end of 2017?',
 'q81097aec': 'containerboards net sales represented what percentage of industrial packaging sales in 2005?',
 'q8232eeda': 'what percentage of total debt maturity occurred in 2018 and thereafter?',
 'q82c368f2': 'what was the total impairment relating to us assets?',
 'q83dfd0c2': "What's the sum of Software and IT maintenance expenses of 2017, Customer deposits of Less Than 1 Year, and Client claims and refunds of 2016 ?",
 'q84448792': 'What is the sum of the Net investment income and Total revenue in the sections where Required interest on net reserves is positive?',
 'q8332f334': "What's the sum of Cost of sales of Year Ended December 31, 2016, Decreases in current period tax positions, and Total Year Ended December 31, 2005 of Balance at End of Period ?",
 'q83905290': 'what is the percentage change in interest expense-net , from 2015 to 2016?',
 'q84a187b2': 'What was the average value of the amount for Europe, the amount for Middle East and Africa , the amount for Asia-Pacific in 2017 ?',
 'q833c8228': "What's the total amount of Management and financial advice fees, Distribution fees, Net investment income and Premiums in 2013? (in million)",
 'q85c8bb88': "In the year with lowest amount of Commercial for TotalLoans, what's the increasing rate of Equipment lease financing for TotalLoans?",
 'q8144794e': "In the year with lowest amount of Distribution fees, what's the increasing rate of Net investment income? (in %)",
 'q84abfc2e': 'What is the sum of the Notebooks/Mobile Devices in the years where Netcomm Products is greater than 1400? (in millions)',
 'q811aabe6': 'What is the proportion of Asset Management to the total Mortgage and other loans receivable, net of allowance in 2006?',
 'q811d0d0a': 'What is the growing rate of Net credit losses in the year with the most Provision for benefits and claims?',
 'q82364166': "In the year with largest amount of Product revenue, what's the sum of Product revenue and Service and other revenue ? (in million)",
 'q83c3dbba': 'What will Long-term debt reach in 2010 if it continues to grow at its current rate?',
 'q8258ff9e': 'What is the sum of Home equity in 2011 and Operating lease obligations for Total? (in million)',
 'q84360b04': 'Which year is Granted for shares(in thousands) the most?',
 'q8397ee9c': 'Which year is Cash and cash equivalents the most?',
 'q818cb290': 'What is the sum of Net written premiums in the range of 1 and 3000 in 2014? (in million)',
 'q8203fe68': 'what was the percentage change in share-based compensation expense between 2012 and 2013?',
 'q82f207b6': 'Which element makes up more than 20% of the total equity securities for Level 1 of U.S. defined benefit pension plans in 2011?',
 'q83e3e52c': 'In terms of Assets,which year is Fair Values of Total derivatives designated as hedging instruments on December 31 smaller than 100000 thousand?',
 'q82374f34': 'What is the amount of Commercial and Commercial realestate in the years with the least Commercial for Gross Charge-offs ? (in million)',
 'q83e16b08': 'what was the sum of the shares purchase discount from 2015 to 2017 in millions',
 'q830208be': 'What is the average value of Total operating revenues for Corporate Benefit Funding, Auto & Home, and International ? (in million)',
 'q83554574': "In the year with largest amount of SquareFeet of Total Consolidated Portfolio, what's the increasing rate of Ann. RentRevenue of Total Consolidated Portfolio?",
 'q848f1da2': 'What was the average value of proceeds from sales of investments, proceeds from maturities of investments,proceeds from significant disposals in 2016 for Citigroup consolidated? (in million)',
 'q84494d40': "What's the current increasing rate of GAAP of Operating Income?",
 'q83562c00': 'When does Net interest income reach the largest value?',
 'q81cfaef6': "What's the greatest value of Premiums earned for Twelve Months Ended December 31, 2015",
 'q821eb91a': 'considering the year 2006 , what is the percentual fluctuation of the return provided by s&p 500 and the one provided by old peer group?',
 'q83ee4b48': "What's the increasing rate of Total segment in 2016 for Total Incurred?",
 'q8284743a': "What's the sum of elements in 2014? (in million)",
 'q823ddc1e': 'percent change of average shares outstanding when taking dilution into consideration in 2008?',
 'q8543ee4e': 'Which year is Operating revenues for Electric the most?',
 'q82d0e284': 'As As the chart 4 shows,what do all Total revenues sum up, excluding the Total revenues for Retirement Products and the Total revenues for Corporate Benefit Funding? (in million)',
 'q820e4ada': 'what is the average price of the increased electricity usage per gwh?',
 'q81661522': 'In the year with the most Granted for shares(in thousands), what is the growth rate of Outstanding ? (in %)',
 'q81719e24': 'What is the sum of Net credit losses in 2009 and Gains on sales of real estate and other in 2006? (in million)',
 'q83fd9170': 'What is the sum of Case reserves of 2008 Ceded, and Balance, end of year of 2009 ?',
 'q83baea32': 'What is the percentage of all Cash and cash equivalents and Unsettled fund receivables that are positive to the total amount, in 2011 ?',
 'q81d04c30': 'What is the growing rate of Amplifiers/Radio frequency in table 0 in the year with the most Converters in table 0?',
 'q84f2c618': 'What is the sum of the Second Quarter 2012 in the sections where Six Months is positive? (in million)',
 'q83c04efa': 'What was the average value of Tier 1 capital, Risk-weighted, Adjusted average for Basel III Standardized Transitional in 2016 ? (in million)',
 'q83cf55b2': 'Does the value of Future cash inflows for Total in 2003 greater than that in 2002 ?',
 'q82384b82': "What's the total value of all Value (In millions) that are in the range of 400 and 1000 in 2011? (in million)",
 'q826ed10c': "What's the sum of all Shares that are positive in 2017?",
 'q8445e3ee': 'What is the growing rate of Common equity tier 1 capital in the year with the most Standardized Approach?',
 'q815dd65a': 'In which year is Commercial Utilized Loans and leases positive?',
 'q817a53d4': "In the year with largest amount of Office Net Charge-offs in table 3, what's the increasing rate of Office Net Charge-offs in table 3?",
 'q8302f030': "What's the growth rate of Segment net sales in 2012?",
 'q83ecfa72': "For the section where the BALANCE, JANUARY 1, 2007 is negative, what's the value of the BALANCE, DECEMBER 31, 2007 ? (in million)",
 'q83542c84': "What's the total amount of Town Grove, LLC, Avalon Del Rey, LLC, CVP I, LLC and Town Run Associates in 2007?",
 'q839b24cc': 'If Goodwill and other intangible assets, net develops with the same growth rate in 2017, what will it reach in 2018? (in million)',
 'q83880a04': 'what was the total research and development from december 312017 to 2015 in millions',
 'q82573bfa': 'Does Case reserves inCeded keeps increasing each year between 2008 and 2009?',
 'q83206f84': 'If Total assets for Assumed develops with the same growth rate in 2014, what will it reach in 2015? (in million)',
 'q84fb6e6c': 'What was the total amount of the Total commercial lending in the years where Total commercial lending greater than 0? (in million)',
 'q826da55c': "In the year with larger amount for Europe, what's the increasing rate of the amount for Asia-Pacific ?",
 'q853b5e6e': "What's the growing rate of Total Forward Hedged Revenues in 2019?",
 'q82dca556': 'what is the growth rate in net revenue for entergy wholesale commodities in 2013?',
 'q84e55370': "What's the increasing rate of Total operating revenues in 2011?",
 'q8198bd92': "What's the growth rate of Net income of the Fourth Quarter in 2016?",
 'q8518ff4a': 'what was the total refined products trunk lines production in tbd for the three year period?',
 'q82be72ac': 'What is the sum of Capital lease obligations for payments due by period ? (in thousand)',
 'q85724ac8': 'What was the total amount of the Global equity and equity-related in the years where Global long-term debt greater than 7 for Market Share ?',
 'q8556c10e': 'what was the percentage change in fuel surcharge program freight revenue from 2013 to 2014?',
 'q82581dc2': 'What is the average amount of 2019 Notes of 2013, and Granted of Number of shares ?',
 'q81bc4a1e': 'What do all Benefits earned during the year sum up, excluding those negative ones in 2010 for Pension plans ? (in million)',
 'q81520e92': 'Is the total amount of all elements in 2014 greater than that in 2013 for CHANGE IN PROJECTED BENEFIT OBLIGATION for Con Edison?',
 'q858b5c20': "In the year with largest amount of Net investment income in table 1, what's the sum of revenues in table 1? (in millions)",
 'q81cb3060': 'When does Projected benefit obligation at beginning of year f Con Edison reach the largest value?',
 'q84dd9f7c': 'What is the average amount of Reserve for unearned premiums of 2014 As Reported, and Expired of Weighted Average Exercise Price ?',
 'q84e682ea': 'What will adjusted total assets be like in 2018 if it develops with the same increasing rate as current? (in dollars in millions)',
 'q81566442': 'What was the total amount of Expenses in 2008 for Amount? (in thousand)',
 'q838b6d0c': 'at december 31 , 2015 , what percent of the environmental-related reserves related to environmental-related asset retirement obligations ?',
 'q834fefca': "In the year with largest amount of Regulated natural gas, what's the increasing rate of Nonregulated electric and other?",
 'q842fefc6': 'Does Planned generation (TWh) keeps increasing each year between 2005 and 2006?',
 'q8300ab0e': 'Which level is U.S. Treasuries of Fixed Income Securities the highest?',
 'q81392cb0': "What's the sum of the Net investment income in the years where Other income is positive? (in million)",
 'q853e847c': 'What is the average value of Total net revenue for Reported Results, Fully taxable-equivalent adjustment, and Managed basis ? (in million)',
 'q859daefc': 'Which year is Estimated Fair Value in terms of Other the most?',
 'q836cd57c': 'In which section the sum of segment in 2015 has the highest value?',
 'q810fb0f6': 'What was the total amount of Allowance greater than 270 in 2018? (in million)',
 'q82b28b22': "In the year with lowest amount of Sales Commissions, what's the increasing rate of Occupancy and Equipment?",
 'q8384b3ea': "What's the sum of Group retirement products of Net Investment Income, Cash at end of year of 2011, and Cash at end of year of 2010 ?",
 'q81d7599e': "What's the average of US SBU in 2014, 2013, and 2012? (in million)",
 'q853c2a92': 'What is the sum of Income (loss) before income taxes and minority interest of As Reported in 2006 and Sales in 2003? (in million)',
 'q81d3a056': 'If Americas develops with the same growth rate in 2004, what will it reach in 2005? (in million)',
 'q849d08a4': 'What will Premiums reach in 2012 if it continues to grow at its current rate? (in million)',
 'q811c3614': 'what was the percentage change in the allowance for loan losses from 2008 to 2009?',
 'q82c9a85c': 'by how much did the fair value of stock-based performance units outstanding decrease from 2016 to 2018?',
 'q83bc7cbc': 'How much of March 31, 2008 is there in total without Operating revenues and Operating income? (in Thousand)',
 'q8175db10': 'what is the percent change in average cds that were excluded between 2013 and 2014?',
 'q82c2627c': "What's the total amount of Subtotal analog signal processing without those Subtotal analog signal processing smaller than 500000, in 2014?",
 'q82efcc80': 'What is the average amount of Reinsurance assets of 2018 As Reported, and Cash provided by operating activities of 2014 ?',
 'q82864972': 'When does Total calendar year effect reach the largest value?',
 'q82b4cc20': 'what is the percentage change in rent expenses for operating leases in 2010 compare to 2009?',
 'q84ceb836': 'Which year is Other borrowings the highest in terms of Carrying Value?',
 'q82871b7c': 'what was the percentage change in the free cash flow from 2014 to 2015',
 'q847a93dc': 'How much of profit before taxes is there in total (in 2017) without U.S. tax reform impact and Gain on sale of equity investment? (in million)',
 'q83e70dd8': 'How many Share repurchase program exceed the average of Share repurchase program in October, 2013?',
 'q856d40e6': 'In which section the sum ofProduct revenues, net has the highest value?',
 'q81da9686': "In the section with lowest amount of Sales, what's the increasing rate of Fair Value ? (in %)",
 'q81f778aa': 'what are the total current assets of metropolitan?',
 'q82e4317c': 'Which year is Standardized measure of discounted future net cash flows relating to proved oil and gas reserves(a) for Total the most?',
 'q845eabea': 'If Fixed income of Active develops with the same increasing rate in2016, what will it reach in 2017? (in million)',
 'q836b9360': "In the year with largest amount of Granted of Shares in Table 3, what's the increasing rate of Net reserves in Table 4?",
 'q815893ca': 'what was the percentage change in the the fair value of our foreign currency forward contracts from 2008 to 2009',
 'q8290c910': 'What is the ratio of all value that are in the range of 400 and 1000 to the sum of value, in 2011?',
 'q8435886e': '% ( % ) change of the dilutive effect from 2006-2008',
 'q837b54d0': 'What is the total amount of Net sales of 2014, and Notes Payable of 2008 Carrying Amounts ?',
 'q8580ff64': 'Which year is Service cost for Pension Benefits the lowest?',
 'q81dc665a': 'If China develops with the same growth rate in 2013, what will it reach in 2014? (in million)',
 'q83d4ede2': "In the year with largest amount of Fair Value for Aaa, what's the growing rate of Fair Value for Aa?",
 'q83e4d1ee': 'What will Balance of Derivatives be like in 2009 if it develops with the same increasing rate as current? (in dollars in millions)',
 'q8159e19e': 'Which year is Residential mortgage for Recoveries of loans and leases previously charged off the most?',
 'q821d9148': 'In which section is Alpine Country smaller than Alpine Village ?',
 'q8247de8a': 'Which year is the amount of Benefit obligation at year end for Pension Benefits larger?',
 'q852a4c64': 'What was the average value of the Fixed maturities: Foreign government bonds for AmortizedCost or Cost in the years where Corporate securities is positive for AmortizedCost or Cost? (in million)',
 'q84e8101a': "What's the growth rate of ABO less fair value of plan assets of Pension Benefits in 2015?",
 'q81344b3c': "what's the total amount of Loss expenses Casualty of 2008 Gross, and Case reserves of 2009 Gross ?",
 'q85cc7e58': "In the year with lowest amount of Interruptible sales in thousands of Dt Delivered, what's the increasing rate of Total firm sales and transportation? (in %)",
 'q84e182f4': 'what is the roi of an investment in loews common stock from 2011 to 2012?',
 'q83cdbf9a': 'What is the ratio of Construction to the total in2015 for Commercial real estate?',
 'q83caeaea': 'what is the percentage change in common shareholders 2019 equity due to the adjustments presented in the table to reach basel iii cet1?',
 'q843df09e': 'What is the sum of the Price/mix-1 in the sections where Volume – Units is positive?',
 'q81db3f50': "What's the total amount of the Gas utility operations in the years where lectric utility operations is greater than 1?",
 'q82c4fd2a': 'Does the value of Fixed income markets in 2004 greater than that in 2003?',
 'q828a58aa': 'If Total segment develops with the same increasing rate in 2016 for Total Incurred, what will it reach in 2017 for Total Incurred? (in million)',
 'q837a4e78': "What's the average of the Private equity/venture capital in the years where SVB Capital Partners II, LP for Carrying value(as reported) for December 31, is positive? (in thousand)",
 'q8441a2de': 'What do all Change, net of taxes sum up, excluding those negative ones in 2015? (in million)',
 'q84d56a96': 'What is the sum of Cash and cash equivalents and marketable securities, Inventories and Total assets in 2014? (in million)',
 'q85b3b076': 'What is the sum of the Tier 1 capital in the years where CET1 capital greater for Basel III Standardized Transitional is greater than 18300? (in million)',
 'q817f6202': 'Which year is Total calendar year effect the most?',
 'q83c7a90c': "In the year with lowest amount of TRICARE subtotal, what's the increasing rate of Commercial and other?",
 'q8241c7b6': 'What is the percentage of all Qualifying Accounting Hedges-2 that are positive to the total amount, in 2010 for Gross Derivative Assets?',
 'q81b8fb70': 'What is the sum of Commercial paper of 2011 Amortized Cost, Net sales of 2011, and Net sales of 2013 ?',
 'q8542325c': 'In which year is Net earnings in As Reported positive?',
 'q835b5ee6': 'What will Interest cost on benefit obligation in U.S. pension plans be like in 2017 if it develops with the same increasing rate as current? (in million)',
 'q81439f7e': 'What will Professional services be like in 2012 if it develops with the same increasing rate as current?',
 'q838d6486': 'How much of Home equity is there in total without California and New York?',
 'q834d2524': 'what percentage of the aggregate consideration for the greenline acquisition was paid to the sellers in 2009 based on the 2008 earn-out target?',
 'q8277c280': "In the years with lowest amount of Operating lease obligations in table 1, what's the increasing rate of Pension and other postretirement cash requirements in table 1?",
 'q828e37cc': 'by what percentage did protect carrying values of excess inventories increase from 2002 to 2003?',
 'q832dd8e0': "In the year with largest amount of Pension plans, what's the increasing rate of Benefits earned during the year?",
 'q83576886': 'what is the highest total amount of Other? (in million)',
 'q85a20326': 'what is the percentage increase in total stock-based compensation expense from 2009 to 2010?',

In [11]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /Users/mac/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [12]:
sent = multiheirtt_task.queries['q81e448f2'].lower()

stop_words = set(stopwords.words('english'))

word_tokens = word_tokenize(sent)
word_tokens

['considering',
 'the',
 'years',
 '2015-2016',
 ',',
 'what',
 'was',
 'the',
 'decrease',
 'observed',
 'in',
 'the',
 'expense',
 'for',
 'severance',
 'and',
 'other',
 'benefits',
 '?']

TypeError: list indices must be integers or slices, not tuple

In [ ]:
im

ModuleNotFoundError: No module named 'nltk'