

### 3.2 Vector Search + RAG Fusion

### 3.3 Hybrid search + Reranking

In [1]:
import os
import numpy as np
import pandas as pd

from dotenv import load_dotenv
from langchain_core.documents import Document
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_google_genai import GoogleGenerativeAIEmbeddings
from financerag.task import *
from financerag.retrieval import DenseRetrieval
from langchain_text_splitters.base import TextSplitter
pd.set_option('display.max_colwidth', 400)
%reload_ext autoreload

In [ ]:
load_dotenv(".env")
GG_API_KEY = os.environ.get('GOOGLE_API_KEY')
PINECONE_API_KEY = os.environ.get('PINECONE_API_KEY')

In [4]:
# Set up vector database
import faiss
from langchain_community.docstore.in_memory import InMemoryDocstore
from langchain_community.vectorstores import FAISS
embeddings = GoogleGenerativeAIEmbeddings(model = "models/text-embedding-004")
index = faiss.IndexFlatL2(len(embeddings.embed_query("hello world")))

vector_store = FAISS(
    embedding_function=embeddings,
    index=index,
    docstore=InMemoryDocstore(),
    index_to_docstore_id={},
)

In [4]:
import torch # type: ignore
torch.__version__

'2.3.0.dev20240311'

In [7]:
if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    x = torch.ones(1, device=mps_device)
    print (x)
else:
    print ("MPS device not found.")

tensor([1.], device='mps:0')

In [3]:
# Get dataset name first
import os
dataset_names = []
for f in os.listdir('finance_dataset'):
    if f.endswith("tsv"):
       dataset_names.append(f.split('_')[0])
dataset_names

['MultiHeirtt',
 'FinQA',
 'FinanceBench',
 'ConvFinQA',
 'FinQABench',
 'TATQA',
 'FinDER']

In [10]:
CHUNK_SIZE = 2000
CHUNK_OVERLAP = 300
text_splitter = RecursiveCharacterTextSplitter(chunk_size=CHUNK_SIZE, chunk_overlap=CHUNK_OVERLAP)

In [ ]:
# Idea for optimizing the retrieved result
# Find out the largest possible length in each corpus
# Take # of splits = maxLen / (chunk_size - chunk_overlap)
# Top_k must be (#splits + 1) * 10 -> max(doc_size +)
# Test to see result first!

In [15]:
df = pd.read_json('finance_dataset/tatqa_corpus.jsonl/corpus.jsonl', lines = True)
df['text'].str.len().max()

14625

In [31]:
import logging 

logging.info('hellow rod')

In [23]:
dataset_name = dataset_names[0]
task_variable = f"{dataset_name.lower()}_task"
script_string = f"""
# {dataset_name} Task
print(f"{dataset_name} task")
{task_variable} = {dataset_name}Task()
{task_variable}.load()
{task_variable}_max_len = np.max([len(text) for text in {task_variable}.corpus.values()])
{task_variable}_top_k = ({task_variable}_max_len // (CHUNK_SIZE - CHUNK_OVERLAP) + 1) * 10
{task_variable}_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = {task_variable}.metadata.dataset_name)
{task_variable}_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = {task_variable}.corpus, saved_index = True)
{task_variable}.retrieve(retriever = {task_variable}_retriever, top_k = {task_variable}_top_k)
{task_variable}.save_retrieved_results()
"""
print(script_string)

# MultiHeirtt Task
print(f"MultiHeirtt task")
multiheirtt_task = MultiHeirttTask()
multiheirtt_task.load()
multiheirtt_task_max_len = np.max([len(text) for text in multiheirtt_task.corpus.values()])
multiheirtt_task_top_k = (multiheirtt_task_max_len // (CHUNK_SIZE - CHUNK_OVERLAP) + 1) * 10
print("Top k for multiheirtt_task:" multiheirtt_task_top_k)

In [37]:
# MultiHeirtt Task
print(f"MultiHeirtt task")
multiheirtt_task = MultiHeirttTask()
multiheirtt_task.load()
multiheirtt_task_max_len = np.max([len(text) for text in multiheirtt_task.corpus.values()])
multiheirtt_task_top_k = (multiheirtt_task_max_len // (CHUNK_SIZE - CHUNK_OVERLAP) + 1) * 10 + 10
print("Top k for multiheirtt_task:", multiheirtt_task_top_k)

MultiHeirtt task
Top k for multiheirtt_task: 120

In [38]:
for dataset_name in dataset_names:
    task_variable = f"{dataset_name.lower()}_task"
    script_string = f"""
    # {dataset_name} Task
    print(f"{dataset_name} task")
    {task_variable} = {dataset_name}Task()
    {task_variable}.load()
    {task_variable}_max_len = np.max([len(text) for text in {task_variable}.corpus.values()])
    {task_variable}_top_k = ({task_variable}_max_len // (CHUNK_SIZE - CHUNK_OVERLAP) + 1) * 10 + 10
    {task_variable}_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = {task_variable}.metadata.dataset_name)
    {task_variable}_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = {task_variable}.corpus, saved_index = False)
    {task_variable}.retrieve(retriever = {task_variable}_retriever, top_k = {task_variable}_top_k)
    {task_variable}.save_retrieved_results()
    """
    print(script_string)

    # MultiHeirtt Task
    print(f"MultiHeirtt task")
    multiheirtt_task = MultiHeirttTask()
    multiheirtt_task.load()
    multiheirtt_task_max_len = np.max([len(text) for text in multiheirtt_task.corpus.values()])
    multiheirtt_task_top_k = (multiheirtt_task_max_len // (CHUNK_SIZE - CHUNK_OVERLAP) + 1) * 10 + 10
    multiheirtt_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = multiheirtt_task.metadata.dataset_name)
    multiheirtt_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = multiheirtt_task.corpus, saved_index = False)
    multiheirtt_task.retrieve(retriever = multiheirtt_task_retriever, top_k = multiheirtt_task_top_k)
    multiheirtt_task.save_retrieved_results()


    # FinQA Task
    print(f"FinQA task")
    finqa_task = FinQATask()
    finqa_task.load()
    finqa_task_max_len = np.max([len(text) for text in finqa_task.corpus.values()])
    finqa_task_top_k = (finqa_task_max_len // (CHUNK_SIZE - CHUNK_OVERLAP) + 1) * 10 + 10
    finqa_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = finqa_task.metadata.dataset_name)
    finqa_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = finqa_task.corpus, saved_index = False)
    finqa_task.retrieve(retriever = finqa_task_retriever, top_k = finqa_task_top_k)
    finqa_task.save_retrieved_results()


    # FinanceBench Task
    print(f"FinanceBench task")
    financebench_task = FinanceBenchTask()
    financebench_task.load()
    financebench_task_max_len = np.max([len(text) for text in financebench_task.corpus.values()])
    financebench_task_top_k = (financebench_task_max_len // (CHUNK_SIZE - CHUNK_OVERLAP) + 1) * 10 + 10
    financebench_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = financebench_task.metadata.dataset_name)
    financebench_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = financebench_task.corpus, saved_index = False)
    financebench_task.retrieve(retriever = financebench_task_retriever, top_k = financebench_task_top_k)
    financebench_task.save_retrieved_results()


    # ConvFinQA Task
    print(f"ConvFinQA task")
    convfinqa_task = ConvFinQATask()
    convfinqa_task.load()
    convfinqa_task_max_len = np.max([len(text) for text in convfinqa_task.corpus.values()])
    convfinqa_task_top_k = (convfinqa_task_max_len // (CHUNK_SIZE - CHUNK_OVERLAP) + 1) * 10 + 10
    convfinqa_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = convfinqa_task.metadata.dataset_name)
    convfinqa_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = convfinqa_task.corpus, saved_index = False)
    convfinqa_task.retrieve(retriever = convfinqa_task_retriever, top_k = convfinqa_task_top_k)
    convfinqa_task.save_retrieved_results()


    # FinQABench Task
    print(f"FinQABench task")
    finqabench_task = FinQABenchTask()
    finqabench_task.load()
    finqabench_task_max_len = np.max([len(text) for text in finqabench_task.corpus.values()])
    finqabench_task_top_k = (finqabench_task_max_len // (CHUNK_SIZE - CHUNK_OVERLAP) + 1) * 10 + 10
    finqabench_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = finqabench_task.metadata.dataset_name)
    finqabench_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = finqabench_task.corpus, saved_index = False)
    finqabench_task.retrieve(retriever = finqabench_task_retriever, top_k = finqabench_task_top_k)
    finqabench_task.save_retrieved_results()


    # TATQA Task
    print(f"TATQA task")
    tatqa_task = TATQATask()
    tatqa_task.load()
    tatqa_task_max_len = np.max([len(text) for text in tatqa_task.corpus.values()])
    tatqa_task_top_k = (tatqa_task_max_len // (CHUNK_SIZE - CHUNK_OVERLAP) + 1) * 10 + 10
    tatqa_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = tatqa_task.metadata.dataset_name)
    tatqa_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = tatqa_task.corpus, saved_index = False)
    tatqa_task.retrieve(retriever = tatqa_task_retriever, top_k = tatqa_task_top_k)
    tatqa_task.save_retrieved_results()


    # FinDER Task
    print(f"FinDER task")
    finder_task = FinDERTask()
    finder_task.load()
    finder_task_max_len = np.max([len(text) for text in finder_task.corpus.values()])
    finder_task_top_k = (finder_task_max_len // (CHUNK_SIZE - CHUNK_OVERLAP) + 1) * 10 + 10
    finder_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = finder_task.metadata.dataset_name)
    finder_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = finder_task.corpus, saved_index = False)
    finder_task.retrieve(retriever = finder_task_retriever, top_k = finder_task_top_k)
    finder_task.save_retrieved_results()

In [39]:
# MultiHeirtt Task
print(f"MultiHeirtt task")
multiheirtt_task = MultiHeirttTask()
multiheirtt_task.load()
multiheirtt_task_max_len = np.max([len(text) for text in multiheirtt_task.corpus.values()])
multiheirtt_task_top_k = (multiheirtt_task_max_len // (CHUNK_SIZE - CHUNK_OVERLAP) + 1) * 10 + 10
multiheirtt_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = multiheirtt_task.metadata.dataset_name)
multiheirtt_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = multiheirtt_task.corpus, saved_index = False)
multiheirtt_task.retrieve(retriever = multiheirtt_task_retriever, top_k = multiheirtt_task_top_k)
multiheirtt_task.save_retrieved_results()


# FinQA Task
print(f"FinQA task")
finqa_task = FinQATask()
finqa_task.load()
finqa_task_max_len = np.max([len(text) for text in finqa_task.corpus.values()])
finqa_task_top_k = (finqa_task_max_len // (CHUNK_SIZE - CHUNK_OVERLAP) + 1) * 10 + 10
finqa_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = finqa_task.metadata.dataset_name)
finqa_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = finqa_task.corpus, saved_index = False)
finqa_task.retrieve(retriever = finqa_task_retriever, top_k = finqa_task_top_k)
finqa_task.save_retrieved_results()


# FinanceBench Task
print(f"FinanceBench task")
financebench_task = FinanceBenchTask()
financebench_task.load()
financebench_task_max_len = np.max([len(text) for text in financebench_task.corpus.values()])
financebench_task_top_k = (financebench_task_max_len // (CHUNK_SIZE - CHUNK_OVERLAP) + 1) * 10 + 10
financebench_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = financebench_task.metadata.dataset_name)
financebench_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = financebench_task.corpus, saved_index = False)
financebench_task.retrieve(retriever = financebench_task_retriever, top_k = financebench_task_top_k)
financebench_task.save_retrieved_results()


# ConvFinQA Task
print(f"ConvFinQA task")
convfinqa_task = ConvFinQATask()
convfinqa_task.load()
convfinqa_task_max_len = np.max([len(text) for text in convfinqa_task.corpus.values()])
convfinqa_task_top_k = (convfinqa_task_max_len // (CHUNK_SIZE - CHUNK_OVERLAP) + 1) * 10 + 10
convfinqa_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = convfinqa_task.metadata.dataset_name)
convfinqa_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = convfinqa_task.corpus, saved_index = False)
convfinqa_task.retrieve(retriever = convfinqa_task_retriever, top_k = convfinqa_task_top_k)
convfinqa_task.save_retrieved_results()


# FinQABench Task
print(f"FinQABench task")
finqabench_task = FinQABenchTask()
finqabench_task.load()
finqabench_task_max_len = np.max([len(text) for text in finqabench_task.corpus.values()])
finqabench_task_top_k = (finqabench_task_max_len // (CHUNK_SIZE - CHUNK_OVERLAP) + 1) * 10 + 10
finqabench_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = finqabench_task.metadata.dataset_name)
finqabench_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = finqabench_task.corpus, saved_index = False)
finqabench_task.retrieve(retriever = finqabench_task_retriever, top_k = finqabench_task_top_k)
finqabench_task.save_retrieved_results()


# TATQA Task
print(f"TATQA task")
tatqa_task = TATQATask()
tatqa_task.load()
tatqa_task_max_len = np.max([len(text) for text in tatqa_task.corpus.values()])
tatqa_task_top_k = (tatqa_task_max_len // (CHUNK_SIZE - CHUNK_OVERLAP) + 1) * 10 + 10
tatqa_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = tatqa_task.metadata.dataset_name)
tatqa_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = tatqa_task.corpus, saved_index = False)
tatqa_task.retrieve(retriever = tatqa_task_retriever, top_k = tatqa_task_top_k)
tatqa_task.save_retrieved_results()


# FinDER Task
print(f"FinDER task")
finder_task = FinDERTask()
finder_task.load()
finder_task_max_len = np.max([len(text) for text in finder_task.corpus.values()])
finder_task_top_k = (finder_task_max_len // (CHUNK_SIZE - CHUNK_OVERLAP) + 1) * 10 + 10
finder_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = finder_task.metadata.dataset_name)
finder_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = finder_task.corpus, saved_index = False)
finder_task.retrieve(retriever = finder_task_retriever, top_k = finder_task_top_k)
finder_task.save_retrieved_results()

MultiHeirtt task

Loading document:: 100%|██████████| 10475/10475 [00:00<00:00, 26025.22it/s]
Retrieving result::  30%|██▉       | 290/974 [39:06<1:32:14,  8.09s/it]

GoogleGenerativeAIError: Error embedding content: 504 Deadline Exceeded

In [1]:
from sentence_transformers import CrossEncoder

/Users/mac/Desktop/Code/Personal_Project/DeepLearningProject/RAG_Project/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [11]:
from nltk.tokenize import word_tokenize
from langchain_community.retrievers import BM25Retriever
retriever = BM25Retriever.from_documents(
    [
        Document(page_content="foo"),
        Document(page_content="bar"),
        Document(page_content="world"),
        Document(page_content="hello"),
        Document(page_content="foo bar"),
    ],
    k=2,
    preprocess_func=word_tokenize,
)

result = retriever.invoke("bar")
result

[Document(metadata={}, page_content='bar'),
 Document(metadata={}, page_content='foo bar')]

In [2]:
# 1. Load a pretrained CrossEncoder model
model = CrossEncoder("cross-encoder/ms-marco-MiniLM-L6-v2", device = 'cpu')

# The texts for which to predict similarity scores
query = "How many people live in Berlin?"
passages = [
    "Berlin had a population of 3,520,031 registered inhabitants in an area of 891.82 square kilometers.",
    "Berlin has a yearly total of about 135 million day visitors, making it one of the most-visited cities in the European Union.",
    "In 2013 around 600,000 Berliners were registered in one of the more than 2,300 sport and fitness clubs.",
]

# 2a. Either predict scores pairs of texts
scores = model.predict([(query, passage) for passage in passages])
print(scores)
# => [8.607139 5.506266 6.352977]

# 2b. Or rank a list of passages for a query
ranks = model.rank(query, passages, return_documents=True)

print("Query:", query)
for rank in ranks:
    print(f"- #{rank['corpus_id']} ({rank['score']:.2f}): {rank['text']}")

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
[8.607143  5.506265  6.3529806]
Query: How many people live in Berlin?
- #0 (8.61): Berlin had a population of 3,520,031 registered inhabitants in an area of 891.82 square kilometers.
- #2 (6.35): In 2013 around 600,000 Berliners were registered in one of the more than 2,300 sport and fitness clubs.
- #1 (5.51): Berlin has a yearly total of about 135 million day visitors, making it one of the most-visited cities in the European Union.

In [ ]:
# MultiHeirtt Task
multiheirtt_task = MultiHeirttTask()
multiheirtt_task.load()
multiheirtt_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = multiheirtt_task.metadata.dataset_name)
multiheirtt_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = multiheirtt_task.corpus, saved_index = True)
multiheirtt_task.retrieve(retriever = multiheirtt_task_retriever)
multiheirtt_task.save_retrieved_results()

Loading document:: 100%|██████████| 10475/10475 [00:00<00:00, 42579.02it/s]

Successfully saved index of vector store to path : faiss_index/multiheirtt_index
Saved result successfully to ./financerag_result/multiheirtt_result.csv!

In [ ]:
# FinQA Task
finqa_task = FinQATask()
finqa_task.load()
finqa_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = finqa_task.metadata.dataset_name)
finqa_task_retriever.load_corpus_for_searching_without_splitting(finqa_task.corpus, saved_index = True)
finqa_task.retrieve(retriever = finqa_task_retriever)
finqa_task.save_retrieved_results()

Loading document: 100%|██████████| 2789/2789 [00:00<00:00, 151775.10it/s]

Successfully saved index of vector store to path : faiss_index/finqa_index

Retrieving result:: 100%|██████████| 1147/1147 [07:21<00:00,  2.60it/s]

Saved result successfully to ./financerag_result/finqa_result.csv!

In [13]:

# FinanceBench Task
financebench_task = FinanceBenchTask()
financebench_task.load()
financebench_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = financebench_task.metadata.dataset_name)
financebench_task_retriever.load_corpus_for_searching(financebench_task.corpus, saved_index = True)
financebench_task.retrieve(retriever = financebench_task_retriever)
financebench_task.save_retrieved_results()

Loading document: 100%|██████████| 180/180 [00:00<00:00, 131942.45it/s]

Successfully saved index of vector store to path : faiss_index/financebench_index

Retrieving result:: 100%|██████████| 150/150 [01:02<00:00,  2.42it/s]

Saved result successfully to ./financerag_result/financebench_result.csv!

In [ ]:
# ConvFinQA Task
convfinqa_task = ConvFinQATask()
convfinqa_task.load()
convfinqa_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = convfinqa_task.metadata.dataset_name)
convfinqa_task_retriever.load_corpus_for_searching_without_splitting(convfinqa_task.corpus, saved_index = True)
convfinqa_task.retrieve(retriever = convfinqa_task_retriever)
convfinqa_task.save_retrieved_results()

Loading document: 100%|██████████| 2066/2066 [00:00<00:00, 129481.68it/s]

Successfully saved index of vector store to path : faiss_index/convfinqa_index

Retrieving result:: 100%|██████████| 421/421 [02:37<00:00,  2.67it/s]

Saved result successfully to ./financerag_result/convfinqa_result.csv!

In [15]:

# FinQABench Task
finqabench_task = FinQABenchTask()
finqabench_task.load()
finqabench_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = finqabench_task.metadata.dataset_name)
finqabench_task_retriever.load_corpus_for_searching(finqabench_task.corpus, saved_index = True)
finqabench_task.retrieve(retriever = finqabench_task_retriever)
finqabench_task.save_retrieved_results()

Loading document: 100%|██████████| 92/92 [00:00<00:00, 89592.75it/s]

Successfully saved index of vector store to path : faiss_index/finqabench_index

Retrieving result:: 100%|██████████| 100/100 [00:36<00:00,  2.75it/s]

Saved result successfully to ./financerag_result/finqabench_result.csv!

In [ ]:

# TATQA Task
tatqa_task = TATQATask()
tatqa_task.load()
tatqa_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = tatqa_task.metadata.dataset_name)
tatqa_task_retriever.load_corpus_for_searching_without_splitting(tatqa_task.corpus, saved_index = True)
tatqa_task.retrieve(retriever = tatqa_task_retriever)
tatqa_task.save_retrieved_results()

Loading document: 100%|██████████| 2756/2756 [00:00<00:00, 182551.12it/s]

Successfully saved index of vector store to path : faiss_index/tatqa_index

Retrieving result:: 100%|██████████| 1663/1663 [15:14<00:00,  1.82it/s]

Saved result successfully to ./financerag_result/tatqa_result.csv!

In [ ]:

# FinDER Task
finder_task = FinDERTask()
finder_task.load()
finder_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = finder_task.metadata.dataset_name)
finder_task_retriever.load_corpus_for_searching_without_splitting(finder_task.corpus, saved_index = True)
finder_task.retrieve(retriever = finder_task_retriever)
finder_task.save_retrieved_results()

Loading document: 100%|██████████| 13862/13862 [00:00<00:00, 20056.98it/s]

Successfully saved index of vector store to path : faiss_index/finder_index

Retrieving result:: 100%|██████████| 216/216 [01:57<00:00,  1.84it/s]

Saved result successfully to ./financerag_result/finder_result.csv!

In [16]:
final_result = pd.DataFrame(columns = ['query_id', 'corpus_id'])

for dataset_name in dataset_names:
    df = pd.read_csv(f"financerag_result/{dataset_name.lower()}_result.csv")
    final_result = pd.concat([final_result, df], axis = 0)

final_result

       query_id     corpus_id
0     q82d4c6ec     d8177a896
1     q82d4c6ec     d8d3fbbaa
2     q82d4c6ec     d85eb42c0
3     q82d4c6ec     d8e817e40
4     q82d4c6ec     d8bb12b52
...         ...           ...
2155     q00218  ADBE20230512
2156     q00218  TSLA20231025
2157     q00218  CPNG20230812
2158     q00218   LIN20230185
2159     q00218     V20230334

[46710 rows x 2 columns]

In [17]:
pd.read_csv('submission.csv')

        query_id      corpus_id
0      q82d4c6ec      d8e404704
1      q82d4c6ec      d87914156
2      q82d4c6ec      d8a3219a8
3      q82d4c6ec      d8c22a07a
4      q82d4c6ec      d88e1c5b2
...          ...            ...
44538     q00218  GOOGL20231203
44539     q00218    JPM20234729
44540     q00218      V20231584
44541     q00218    JPM20237319
44542     q00218      V20231597

[44543 rows x 2 columns]

In [20]:
pd.read_csv('finance_dataset/sample_submission_.csv')

        query_id  corpus_id
0      qd496c6a0  dd4b92b32
1      qd496c6a0  dd4ba2a5a
2      qd496c6a0  dd4be1f98
3      qd496c6a0  dd4ba07d2
4      qd496c6a0  dd4ba02f0
...          ...        ...
46681  q1a741e68  d1b3afaba
46682  q1a741e68  d1b34e18e
46683  q1a741e68  d1b36065e
46684  q1a741e68  d1b33d05a
46685  q1a741e68  d1b32d114

[46686 rows x 2 columns]

In [18]:
final_result.to_csv('submission_bm25.csv', index = False)

In [22]:
final_result.drop_duplicates(subset = ['query_id'])

       query_id      corpus_id
0     q82d4c6ec      d8e404704
10    q855a35a0      d89a6ea36
20    q85384530      d8ce7fc30
30    q842c8af2      d88465f0a
40    q85451756      d8646ec7e
...         ...            ...
2094     q00214  BRK.A20230009
2104     q00215  BRK.A20230404
2114     q00216  BRK.A20232401
2124     q00217  BRK.A20230062
2134     q00218  BRK.A20230594

[4659 rows x 2 columns]

In [28]:
final_queries = pd.DataFrame(columns = ['_id', 'title', 'text'])

for dataset_name in dataset_names:
    df = pd.read_json(f"finance_dataset/{dataset_name.lower()}_queries.jsonl/queries.jsonl", lines = True)
    final_queries = pd.concat([final_queries, df], axis = 0)

final_queries

           _id title                                               text
0    q82d4c6ec        What was the sum of Fourth Quarter without tho...
1    q855a35a0        In which section is Interest income smaller th...
2    q85384530        If Total Forward Hedged Revenues develops with...
3    q842c8af2        what was the ratio of the purchase in december...
4    q85451756        what is the highest total amount of segment in...
..         ...   ...                                                ...
211     q00214        How many distinct insurance underwriting group...
212     q00215        What is the ticker symbol for Berkshire Hathaw...
213     q00216        What is the largest operating segment of the B...
214     q00217        Source of invested assets of insurance busines...
215     q00218                                     Float as of 2023 BRK

[4671 rows x 3 columns]

In [7]:
for dataset_name in dataset_names:
    task_variable = f"{dataset_name.lower()}_task"
    script_string = f"""
    # {dataset_name} Task
    print(f"{dataset_name} task")
    {task_variable} = {dataset_name}Task()
    {task_variable}.load()
    {task_variable}_bm25_retriever = BM25_Retriever()
    retrieved_result = {task_variable}.retrieve(retriever = {task_variable}_bm25_retriever, corpus = {task_variable}.corpus, top_k = 10)
    {task_variable}.save_retrieved_results(retrieved_result = retrieved_result)
    """
    print(script_string)

    # MultiHeirtt Task
    print(f"MultiHeirtt task")
    multiheirtt_task = MultiHeirttTask()
    multiheirtt_task.load()
    multiheirtt_task_bm25_retriever = BM25_Retriever()
    retrieved_result = multiheirtt_task.retrieve(retriever = multiheirtt_task_bm25_retriever, corpus = multiheirtt_task.corpus, top_k = 10)
    multiheirtt_task.save_retrieved_results(retrieved_result = retrieved_result)


    # FinQA Task
    print(f"FinQA task")
    finqa_task = FinQATask()
    finqa_task.load()
    finqa_task_bm25_retriever = BM25_Retriever()
    retrieved_result = finqa_task.retrieve(retriever = finqa_task_bm25_retriever, corpus = finqa_task.corpus, top_k = 10)
    finqa_task.save_retrieved_results(retrieved_result = retrieved_result)


    # FinanceBench Task
    print(f"FinanceBench task")
    financebench_task = FinanceBenchTask()
    financebench_task.load()
    financebench_task_bm25_retriever = BM25_Retriever()
    retrieved_result = financebench_task.retrieve(retriever = financebench_task_bm25_retriever, corpus = financebench_task.corpus, top_k = 10)
    financebench_task.save_retrieved_results(retrieved_result = retrieved_result)


    # ConvFinQA Task
    print(f"ConvFinQA task")
    convfinqa_task = ConvFinQATask()
    convfinqa_task.load()
    convfinqa_task_bm25_retriever = BM25_Retriever()
    retrieved_result = convfinqa_task.retrieve(retriever = convfinqa_task_bm25_retriever, corpus = convfinqa_task.corpus, top_k = 10)
    convfinqa_task.save_retrieved_results(retrieved_result = retrieved_result)


    # FinQABench Task
    print(f"FinQABench task")
    finqabench_task = FinQABenchTask()
    finqabench_task.load()
    finqabench_task_bm25_retriever = BM25_Retriever()
    retrieved_result = finqabench_task.retrieve(retriever = finqabench_task_bm25_retriever, corpus = finqabench_task.corpus, top_k = 10)
    finqabench_task.save_retrieved_results(retrieved_result = retrieved_result)


    # TATQA Task
    print(f"TATQA task")
    tatqa_task = TATQATask()
    tatqa_task.load()
    tatqa_task_bm25_retriever = BM25_Retriever()
    retrieved_result = tatqa_task.retrieve(retriever = tatqa_task_bm25_retriever, corpus = tatqa_task.corpus, top_k = 10)
    tatqa_task.save_retrieved_results(retrieved_result = retrieved_result)


    # FinDER Task
    print(f"FinDER task")
    finder_task = FinDERTask()
    finder_task.load()
    finder_task_bm25_retriever = BM25_Retriever()
    retrieved_result = finder_task.retrieve(retriever = finder_task_bm25_retriever, corpus = finder_task.corpus, top_k = 10)
    finder_task.save_retrieved_results(retrieved_result = retrieved_result)

In [5]:
from financerag.retrieval import BM25, BM25_Retriever

In [7]:

# MultiHeirtt Task
# print(f"MultiHeirtt task")
# multiheirtt_task = MultiHeirttTask()
# multiheirtt_task.load()
# multiheirtt_task_bm25_retriever = BM25_Retriever()
# multiheirtt_task.retrieve(retriever = multiheirtt_task_bm25_retriever, corpus = multiheirtt_task.corpus, top_k = 10)
# multiheirtt_task.save_retrieved_results()


# # FinQA Task
# print(f"FinQA task")
# finqa_task = FinQATask()
# finqa_task.load()
# finqa_task_bm25_retriever = BM25_Retriever()
# finqa_task.retrieve(retriever = finqa_task_bm25_retriever, corpus = finqa_task.corpus, top_k = 10)
# finqa_task.save_retrieved_results()



# FinanceBench Task
print(f"FinanceBench task")
financebench_task = FinanceBenchTask()
financebench_task.load()
financebench_task_bm25_retriever = BM25_Retriever()
retrieved_result = financebench_task.retrieve(retriever = financebench_task_bm25_retriever, corpus = financebench_task.corpus, top_k = 10)
financebench_task.save_retrieved_results(retrieved_result = retrieved_result)


# ConvFinQA Task
print(f"ConvFinQA task")
convfinqa_task = ConvFinQATask()
convfinqa_task.load()
convfinqa_task_bm25_retriever = BM25_Retriever()
retrieved_result = convfinqa_task.retrieve(retriever = convfinqa_task_bm25_retriever, corpus = convfinqa_task.corpus, top_k = 10)
convfinqa_task.save_retrieved_results(retrieved_result = retrieved_result)


# FinQABench Task
print(f"FinQABench task")
finqabench_task = FinQABenchTask()
finqabench_task.load()
finqabench_task_bm25_retriever = BM25_Retriever()
retrieved_result = finqabench_task.retrieve(retriever = finqabench_task_bm25_retriever, corpus = finqabench_task.corpus, top_k = 10)
finqabench_task.save_retrieved_results(retrieved_result = retrieved_result)


# TATQA Task
print(f"TATQA task")
tatqa_task = TATQATask()
tatqa_task.load()
tatqa_task_bm25_retriever = BM25_Retriever()
retrieved_result = tatqa_task.retrieve(retriever = tatqa_task_bm25_retriever, corpus = tatqa_task.corpus, top_k = 10)
tatqa_task.save_retrieved_results(retrieved_result = retrieved_result)


# FinDER Task
print(f"FinDER task")
finder_task = FinDERTask()
finder_task.load()
finder_task_bm25_retriever = BM25_Retriever()
retrieved_result = finder_task.retrieve(retriever = finder_task_bm25_retriever, corpus = finder_task.corpus, top_k = 10)
finder_task.save_retrieved_results(retrieved_result = retrieved_result)

FinanceBench task
Saved result successfully to ./financerag_result/financebench_result.csv!
ConvFinQA task
Saved result successfully to ./financerag_result/convfinqa_result.csv!
FinQABench task
Saved result successfully to ./financerag_result/finqabench_result.csv!
TATQA task
Saved result successfully to ./financerag_result/tatqa_result.csv!
FinDER task
Saved result successfully to ./financerag_result/finder_result.csv!

In [10]:
retrieved_result

{'qd2ac917a': {'dd2adb8d4': 'Exhibit Johnson Johnson Announces Updated Financials and 2023 Guidance Following Completion of the Kenvue Separation Company expects increased 2023 Reported Sales Growth of Operational Sales Growth of and Adjusted Operational Sales Growth of Figures exclude the COVID Vaccine Company expects 2023 Adjusted Reported Earnings Per Share EPS of reflecting increased growth of at the mid point and Adjusted Operational EPS of reflecting increased growth of at the mid point Company reduced outstanding share count by approximately million 2023 guidance reflects only a partial year benefit of approximately million shares or benefit to EPS Company secured billion in cash proceeds from the Kenvue debt offering and initial public offering and maintains of equity stake in Kenvue Company maintains its quarterly dividend of per share New Brunswick N J August 2023 Johnson Johnson NYSE JNJ the Company today announced updates to its financials and 2023 guidance which reflect its operations as a company focused on transformational innovation in Pharmaceutical and MedTech The Company has published a recorded webinar for investors to provide additional context behind the updated financials and 2023 guidance found in this release which may be accessed by visiting the Investors section of the Company s website at webcasts presentations The completion of this transaction uniquely positions Johnson Johnson as a Pharmaceutical and MedTech company focused on delivering transformative healthcare solutions to patients said Joaquin Duato Chairman of the Board and Chief Executive Officer We are incredibly proud of the focus and dedication of our employees worldwide to achieve this milestone which we are confident will unlock near and long term value for all of our stakeholders As previously announced the Company recently completed an exchange offer to finalize the separation of Kenvue Inc formerly Johnson Johnsons Consumer Health business As a result of the completion of the exchange offer Johnson Johnson will now present its Consumer Health business financial results as discontinued operations including a gain of approximately billion in the third quarter of 2023',
  'dd2adb5be': 'Exhibit Johnson Johnson Announces Updated Financials and 2023 Guidance Following Completion of the Kenvue Separation Company expects increased 2023 Reported Sales Growth of Operational Sales Growth of and Adjusted Operational Sales Growth of Figures exclude the COVID Vaccine Company expects 2023 Adjusted Reported Earnings Per Share EPS of reflecting increased growth of at the mid point and Adjusted Operational EPS of reflecting increased growth of at the mid point Company reduced outstanding share count by approximately million 2023 guidance reflects only a partial year benefit of approximately million shares or benefit to EPS Company secured billion in cash proceeds from the Kenvue debt offering and initial public offering and maintains of equity stake in Kenvue Company maintains its quarterly dividend of per share New Brunswick N J August 2023 Johnson Johnson NYSE JNJ the Company today announced updates to its financials and 2023 guidance which reflect its operations as a company focused on transformational innovation in Pharmaceutical and MedTech The Company has published a recorded webinar for investors to provide additional context behind the updated financials and 2023 guidance found in this release which may be accessed by visiting the Investors section of the Company s website at webcasts presentations The completion of this transaction uniquely positions Johnson Johnson as a Pharmaceutical and MedTech company focused on delivering transformative healthcare solutions to patients said Joaquin Duato Chairman of the Board and Chief Executive Officer We are incredibly proud of the focus and dedication of our employees worldwide to achieve this milestone which we are confident will unlock near and long term value for all of our stakeholders As previously announced the Company recently completed an exchange offer to finalize the separation of Kenvue Inc formerly Johnson Johnsons Consumer Health business As a result of the completion of the exchange offer Johnson Johnson will now present its Consumer Health business financial results as discontinued operations including a gain of approximately billion in the third quarter of 2023',
  'dd2afc3f4': 'Note Acquisitions Divestitures Equity Method Investments Licensing Arrangements and Collaborative Arrangements A Acquisitions Trillium On November 2021 we acquired all of the issued and outstanding common stock not already owned by Pfizer of Trillium a clinical stage immuno oncology company developing therapies targeting cancer immune evasion pathways and specific cell targeting approaches for a price of per share in cash for total consideration of billion net of cash acquired As a result Trillium became our wholly owned subsidiary We previously held a ownership investment in Trillium Trilliums lead program TTI is an investigational fusion protein that is designed to block the inhibitory activity of CD a molecule that is overexpressed by a wide variety of tumors We accounted for the transaction as an asset acquisition since the lead asset TTI represented substantially all of the fair value of the gross assets acquired which exclude cash acquired At the acquisition date we recorded a billion charge representing an acquired IPR D asset with no alternative future use in Research and development expenses of which the billion net cash consideration is presented as a cash outflow from operating activities In connection with this acquisition we recorded million of assets acquired primarily consisting of cash and investments Liabilities assumed were approximately million Array On July 2019 we acquired Array a commercial stage biopharmaceutical company focused on the discovery development and commercialization of targeted small molecule medicines to treat cancer and other diseases of high unmet need for per share in cash The total fair value of the consideration transferred was billion billion net of cash acquired In addition million in payments to Array employees for the fair value of previously unvested stock options was recognized as post closing compensation expense and recorded in Restructuring charges and certain acquisition related costs see Note We financed the majority of the transaction with debt and the balance with existing cash',
  'dd2ac6718': 'July 2023 July 2022 July 2023 July 2022 Operating income of revenue Intangible asset amortization Restructuring charges Non GAAP operating income of revenue Effective tax rate Intangible asset amortization Restructuring charges Loss on investments Non GAAP effective tax rate Diluted EPS Intangible asset amortization Restructuring charges Loss on investments Gain on sale of subsidiary net Income tax impact of non GAAP adjustments Non GAAP diluted EPS For additional information regarding the nature of charges discussed below refer to Note Basis of Presentation Note Restructuring and Note Goodwill and Intangible Assets of the Notes to Condensed Consolidated Financial Statements included in this Quarterly Report on Form Q Represents the non cash amortization of definite lived intangible assets associated with acquisitions including customer relationships tradenames and developed technology assets Represents charges related to employee termination benefits and subsequent adjustments from higher than expected employee retention related to previously planned organizational changes Represents the gain on sale of a Mexico subsidiary subsequent to our exit from operations in Mexico The non GAAP adjustments primarily relate to the U S and Mexico As such the forecasted annual income tax charge on the U S non GAAP adjustments is calculated using the statutory tax rate of There is no forecasted annual income tax benefit for Mexico non GAAP items as there is no forecasted annual tax expense on the income in the calculation of GAAP income tax expense Our non GAAP operating income rates decreased in the second quarter and first six months of fiscal 2024 primarily due to unfavorable SG A rates partially offset by favorable gross profit rates Our non GAAP effective tax rate increased in the second quarter of fiscal 2024 primarily due to the prior year resolution of certain discrete tax matters Our non GAAP effective tax rate increased in the first six months of fiscal 2024 primarily due to the prior year resolution of certain discrete tax matters and decreased tax benefits from stock based compensation partially offset by the impact of lower pre tax earnings Our non GAAP diluted EPS decreased in the second quarter and first six months of fiscal 2024 primarily due to the decreases in non GAAP operating income Liquidity and Capital Resources We closely manage our liquidity and capital resources Our liquidity requirements depend on key variables including the level of investment required to support our business strategies the performance of our business capital expenditures dividends credit facilities short term borrowing arrangements and working capital management We modify our approach to managing these variables as changes in our operating environment arise For example capital expenditures and share repurchases are a component of our cash flow and capital management strategy which to a large extent we can adjust in response to economic and other changes in our business environment We have a disciplined approach to capital allocation which focuses on investing in key priorities that support our strategy Cash and cash equivalents were as follows in millions July 2023 January 2023 July 2022 Cash and cash equivalents',
  'dd2adcc02': 'Overview JPMorgan Chase Co JPMorgan Chase or the Firm NYSE JPM a financial holding company incorporated under Delaware law in 1968 is a leading financial services firm based in the United States of America U S with operations worldwide JPMorgan Chase had trillion in assets and billion in stockholders equity as of December 2022 The Firm is a leader in investment banking financial services for consumers and small businesses commercial banking financial transaction processing and asset management Under the J P Morgan and Chase brands the Firm serves millions of customers predominantly in the U S and many of the worlds most prominent corporate institutional and government clients globally',
  'dd2af679c': 'Item Other Events Effective May 2023 PepsiCo Inc PepsiCo terminated the day unsecured revolving credit agreement dated as of May 2022 among PepsiCo as borrower the lenders party thereto and Citibank N A as administrative agent the 2022 Day Credit Agreement There were no outstanding borrowings under the 2022 Day Credit Agreement at the time of its termination On May 2023 PepsiCo entered into a new day unsecured revolving credit agreement the 2023 Day Credit Agreement among PepsiCo as borrower the lenders party thereto and Citibank N A as administrative agent The 2023 Day Credit Agreement enables PepsiCo and its borrowing subsidiaries to borrow up to in U S Dollars and or Euros subject to customary terms and conditions and expires on May 2024 PepsiCo may also upon the agreement of either the then existing lenders or of additional banks not currently party to the 2023 Day Credit Agreement increase the commitments under the 2023 Day Credit Agreement to up to in U S Dollars and or Euros PepsiCo may request renewal of the 2023 Day Credit Agreement for an additional day period or convert any amounts outstanding into a term loan for a period of up to one year which term loan would mature no later than the anniversary of the then effective termination date Subject to certain conditions stated in the 2023 Day Credit Agreement PepsiCo and its borrowing subsidiaries may borrow prepay and reborrow amounts under the 2023 Day Credit Agreement at any time during the term of the 2023 Day Credit Agreement Funds borrowed under the 2023 Day Credit Agreement may be used for general corporate purposes of PepsiCo and its subsidiaries The 2023 Day Credit Agreement contains customary representations and warranties and events of default In the ordinary course of their respective businesses the lenders under the 2023 Day Credit Agreement and their affiliates have engaged and may in the future engage in commercial banking and or investment banking transactions with PepsiCo and its affiliates Effective May 2023 PepsiCo terminated the five year unsecured revolving credit agreement dated as of May 2022 among PepsiCo as borrower the lenders party thereto and Citibank N A as administrative agent the 2022 Five Year Credit Agreement There were no outstanding borrowings under the 2022 Five Year Credit Agreement at the time of its termination On May 2023 PepsiCo entered into a new five year unsecured revolving credit agreement the 2023 Five Year Credit Agreement among PepsiCo as borrower the lenders party thereto and Citibank N A as administrative agent The 2023 Five Year Credit Agreement enables PepsiCo and its borrowing subsidiaries to borrow up to in U S Dollars and or Euros including a swing line subfacility for Euro denominated borrowings permitted to be borrowed on a same day basis subject to customary terms and conditions and expires on May 2028 PepsiCo may also upon the agreement of either the then existing lenders or of additional banks not currently party to the 2023 Five Year Credit Agreement increase the commitments under the 2023 Five Year Credit Agreement to up to in U S Dollars and or Euros PepsiCo may once a year request renewal of the 2023 Five Year Credit Agreement for an additional one year period Subject to certain conditions stated in the 2023 Five Year Credit Agreement PepsiCo and its borrowing subsidiaries may borrow prepay and reborrow amounts under the 2023 Five Year Credit Agreement at any time during the term of the 2023 Five Year Credit Agreement Funds borrowed under the 2023 Five Year Credit Agreement may be used for general corporate purposes of PepsiCo and its subsidiaries The 2023 Five Year Credit Agreement contains customary representations and warranties and events of default In the ordinary course of their respective businesses the lenders under the 2023 Five Year Credit Agreement and their affiliates have engaged and may in the future engage in commercial banking and or investment banking transactions with PepsiCo and its affiliates',
  'dd2ac1056': 'On August 2022 the Company completed the acquisition of equity interest in a Czech Republic company that operates a world class flexible packaging manufacturing plant The purchase consideration of million included a deferred portion of million that was paid in the first quarter of fiscal year 2024 The acquisition is part of the Company s Flexibles reportable segment and resulted in the recognition of acquired identifiable net assets of million and goodwill of million Goodwill is not deductible for tax purposes The fair values of the identifiable net assets acquired and goodwill are based on the Company s best estimate as of June 2023 On March 2023 the Company completed the acquisition of equity interest in a medical device packaging manufacturing site in Shanghai China The purchase consideration of million is subject to customary post closing adjustments The consideration includes contingent consideration of million to be earned and paid in cash over the three years following the acquisition date subject to meeting certain performance targets The acquisition is part of the Company s Flexibles reportable segment and resulted in the recognition of acquired identifiable net assets of million and goodwill of million Goodwill is not deductible for tax purposes The fair values of the contingent consideration identifiable net assets acquired and goodwill are based on the Company s best estimate as of June 2023 and are considered preliminary The Company aims to complete the purchase price allocation as soon as practicable but no later than one year from the date of the acquisition On May 2023 the Company completed the acquisition of a New Zealand based leading manufacturer of state of the art automated protein packaging machines The purchase consideration of million is subject to customary post closing adjustments The consideration includes contingent consideration of million to be earned and paid in cash over the two years following the acquisition date subject to meeting certain performance targets The acquisition is part of the Company s Flexibles reportable segment and resulted in the recognition of acquired identifiable net assets of million and goodwill of million Goodwill is deductible for tax purposes The fair values of the contingent consideration identifiable net assets acquired and goodwill are based on the Company s best estimate as of June 2023 and are considered preliminary The Company aims to complete the purchase price allocation as soon as practicable but no later than one year from the date of the acquisition',
  'dd2af5afe': 'Effective May 2023 PepsiCo terminated the five year unsecured revolving credit agreement dated as of May 2022 among PepsiCo as borrower the lenders party thereto and Citibank N A as administrative agent the 2022 Five Year Credit Agreement There were no outstanding borrowings under the 2022 Five Year Credit Agreement at the time of its termination On May 2023 PepsiCo entered into a new five year unsecured revolving credit agreement the 2023 Five Year Credit Agreement among PepsiCo as borrower the lenders party thereto and Citibank N A as administrative agent The 2023 Five Year Credit Agreement enables PepsiCo and its borrowing subsidiaries to borrow up to in U S Dollars and or Euros including a swing line subfacility for Euro denominated borrowings permitted to be borrowed on a same day basis subject to customary terms and conditions and expires on May 2028 PepsiCo may also upon the agreement of either the then existing lenders or of additional banks not currently party to the 2023 Five Year Credit Agreement increase the commitments under the 2023 Five Year Credit Agreement to up to in U S Dollars and or Euros PepsiCo may once a year request renewal of the 2023 Five Year Credit Agreement for an additional one year period Subject to certain conditions stated in the 2023 Five Year Credit Agreement PepsiCo and its borrowing subsidiaries may borrow prepay and reborrow amounts under the 2023 Five Year Credit Agreement at any time during the term of the 2023 Five Year Credit Agreement Funds borrowed under the 2023 Five Year Credit Agreement may be used for general corporate purposes of PepsiCo and its subsidiaries The 2023 Five Year Credit Agreement contains customary representations and warranties and events of default In the ordinary course of their respective businesses the lenders under the 2023 Five Year Credit Agreement and their affiliates have engaged and may in the future engage in commercial banking and or investment banking transactions with PepsiCo and its affiliates',

In [11]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /Users/mac/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [12]:
sent = multiheirtt_task.queries['q81e448f2'].lower()

stop_words = set(stopwords.words('english'))

word_tokens = word_tokenize(sent)
word_tokens

['considering',
 'the',
 'years',
 '2015-2016',
 ',',
 'what',
 'was',
 'the',
 'decrease',
 'observed',
 'in',
 'the',
 'expense',
 'for',
 'severance',
 'and',
 'other',
 'benefits',
 '?']

TypeError: list indices must be integers or slices, not tuple

In [ ]:
im

ModuleNotFoundError: No module named 'nltk'